/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux 728ef7829fd8 6.8.0-51-generic x86_64"
#define LGL_COMPILED "Fri May  2 10:47:40 UTC 2025"
#define LGL_RELEASED "Fri May  2 10:47:40 UTC 2025"
#define LGL_VERSION "1.0.0"
#define LGL_ID "a04da5b159b4044a11c386232730df9251e8d320"
