/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux f9f98a682cdc 6.8.0-51-generic x86_64"
#define LGL_COMPILED "Mon Apr 28 04:46:32 UTC 2025"
#define LGL_RELEASED "Mon Apr 28 04:46:32 UTC 2025"
#define LGL_VERSION "1.0.0"
#define LGL_ID "724829e7e6dcaffe66d4ddf6e13d3a456591f61c"
