/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux 2e1c7f5010bd 6.8.0-51-generic x86_64"
#define LGL_COMPILED "Sat Apr 26 15:56:59 UTC 2025"
#define LGL_RELEASED "Sat Apr 26 15:56:59 UTC 2025"
#define LGL_VERSION "1.0.0"
#define LGL_ID "32df80a061b4d493f5c4af2891a718092adc53a2"
